// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockIEmailService is an autogenerated mock type for the IEmailService type
type MockIEmailService struct {
	mock.Mock
}

type MockIEmailService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIEmailService) EXPECT() *MockIEmailService_Expecter {
	return &MockIEmailService_Expecter{mock: &_m.Mock}
}

// SendPasswordReset provides a mock function with given fields: email, token
func (_m *MockIEmailService) SendPasswordReset(email string, token string) error {
	ret := _m.Called(email, token)

	if len(ret) == 0 {
		panic("no return value specified for SendPasswordReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIEmailService_SendPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPasswordReset'
type MockIEmailService_SendPasswordReset_Call struct {
	*mock.Call
}

// SendPasswordReset is a helper method to define mock.On call
//   - email string
//   - token string
func (_e *MockIEmailService_Expecter) SendPasswordReset(email interface{}, token interface{}) *MockIEmailService_SendPasswordReset_Call {
	return &MockIEmailService_SendPasswordReset_Call{Call: _e.mock.On("SendPasswordReset", email, token)}
}

func (_c *MockIEmailService_SendPasswordReset_Call) Run(run func(email string, token string)) *MockIEmailService_SendPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIEmailService_SendPasswordReset_Call) Return(_a0 error) *MockIEmailService_SendPasswordReset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIEmailService_SendPasswordReset_Call) RunAndReturn(run func(string, string) error) *MockIEmailService_SendPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// SendUpdateVerificationEmail provides a mock function with given fields: email, code
func (_m *MockIEmailService) SendUpdateVerificationEmail(email string, code string) error {
	ret := _m.Called(email, code)

	if len(ret) == 0 {
		panic("no return value specified for SendUpdateVerificationEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIEmailService_SendUpdateVerificationEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUpdateVerificationEmail'
type MockIEmailService_SendUpdateVerificationEmail_Call struct {
	*mock.Call
}

// SendUpdateVerificationEmail is a helper method to define mock.On call
//   - email string
//   - code string
func (_e *MockIEmailService_Expecter) SendUpdateVerificationEmail(email interface{}, code interface{}) *MockIEmailService_SendUpdateVerificationEmail_Call {
	return &MockIEmailService_SendUpdateVerificationEmail_Call{Call: _e.mock.On("SendUpdateVerificationEmail", email, code)}
}

func (_c *MockIEmailService_SendUpdateVerificationEmail_Call) Run(run func(email string, code string)) *MockIEmailService_SendUpdateVerificationEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIEmailService_SendUpdateVerificationEmail_Call) Return(_a0 error) *MockIEmailService_SendUpdateVerificationEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIEmailService_SendUpdateVerificationEmail_Call) RunAndReturn(run func(string, string) error) *MockIEmailService_SendUpdateVerificationEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendVerificationEmail provides a mock function with given fields: email, code
func (_m *MockIEmailService) SendVerificationEmail(email string, code string) error {
	ret := _m.Called(email, code)

	if len(ret) == 0 {
		panic("no return value specified for SendVerificationEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIEmailService_SendVerificationEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendVerificationEmail'
type MockIEmailService_SendVerificationEmail_Call struct {
	*mock.Call
}

// SendVerificationEmail is a helper method to define mock.On call
//   - email string
//   - code string
func (_e *MockIEmailService_Expecter) SendVerificationEmail(email interface{}, code interface{}) *MockIEmailService_SendVerificationEmail_Call {
	return &MockIEmailService_SendVerificationEmail_Call{Call: _e.mock.On("SendVerificationEmail", email, code)}
}

func (_c *MockIEmailService_SendVerificationEmail_Call) Run(run func(email string, code string)) *MockIEmailService_SendVerificationEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIEmailService_SendVerificationEmail_Call) Return(_a0 error) *MockIEmailService_SendVerificationEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIEmailService_SendVerificationEmail_Call) RunAndReturn(run func(string, string) error) *MockIEmailService_SendVerificationEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIEmailService creates a new instance of MockIEmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIEmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIEmailService {
	mock := &MockIEmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
