// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "write_base/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockIFollowUsecase is an autogenerated mock type for the IFollowUsecase type
type MockIFollowUsecase struct {
	mock.Mock
}

type MockIFollowUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIFollowUsecase) EXPECT() *MockIFollowUsecase_Expecter {
	return &MockIFollowUsecase_Expecter{mock: &_m.Mock}
}

// FollowUser provides a mock function with given fields: ctx, followerID, followeeID
func (_m *MockIFollowUsecase) FollowUser(ctx context.Context, followerID string, followeeID string) error {
	ret := _m.Called(ctx, followerID, followeeID)

	if len(ret) == 0 {
		panic("no return value specified for FollowUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, followerID, followeeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIFollowUsecase_FollowUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FollowUser'
type MockIFollowUsecase_FollowUser_Call struct {
	*mock.Call
}

// FollowUser is a helper method to define mock.On call
//   - ctx context.Context
//   - followerID string
//   - followeeID string
func (_e *MockIFollowUsecase_Expecter) FollowUser(ctx interface{}, followerID interface{}, followeeID interface{}) *MockIFollowUsecase_FollowUser_Call {
	return &MockIFollowUsecase_FollowUser_Call{Call: _e.mock.On("FollowUser", ctx, followerID, followeeID)}
}

func (_c *MockIFollowUsecase_FollowUser_Call) Run(run func(ctx context.Context, followerID string, followeeID string)) *MockIFollowUsecase_FollowUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIFollowUsecase_FollowUser_Call) Return(_a0 error) *MockIFollowUsecase_FollowUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIFollowUsecase_FollowUser_Call) RunAndReturn(run func(context.Context, string, string) error) *MockIFollowUsecase_FollowUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetFollowers provides a mock function with given fields: ctx, userID
func (_m *MockIFollowUsecase) GetFollowers(ctx context.Context, userID string) ([]*domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowers")
	}

	var r0 []*domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIFollowUsecase_GetFollowers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFollowers'
type MockIFollowUsecase_GetFollowers_Call struct {
	*mock.Call
}

// GetFollowers is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockIFollowUsecase_Expecter) GetFollowers(ctx interface{}, userID interface{}) *MockIFollowUsecase_GetFollowers_Call {
	return &MockIFollowUsecase_GetFollowers_Call{Call: _e.mock.On("GetFollowers", ctx, userID)}
}

func (_c *MockIFollowUsecase_GetFollowers_Call) Run(run func(ctx context.Context, userID string)) *MockIFollowUsecase_GetFollowers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIFollowUsecase_GetFollowers_Call) Return(_a0 []*domain.User, _a1 error) *MockIFollowUsecase_GetFollowers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIFollowUsecase_GetFollowers_Call) RunAndReturn(run func(context.Context, string) ([]*domain.User, error)) *MockIFollowUsecase_GetFollowers_Call {
	_c.Call.Return(run)
	return _c
}

// GetFollowing provides a mock function with given fields: ctx, userID
func (_m *MockIFollowUsecase) GetFollowing(ctx context.Context, userID string) ([]*domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowing")
	}

	var r0 []*domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIFollowUsecase_GetFollowing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFollowing'
type MockIFollowUsecase_GetFollowing_Call struct {
	*mock.Call
}

// GetFollowing is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockIFollowUsecase_Expecter) GetFollowing(ctx interface{}, userID interface{}) *MockIFollowUsecase_GetFollowing_Call {
	return &MockIFollowUsecase_GetFollowing_Call{Call: _e.mock.On("GetFollowing", ctx, userID)}
}

func (_c *MockIFollowUsecase_GetFollowing_Call) Run(run func(ctx context.Context, userID string)) *MockIFollowUsecase_GetFollowing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIFollowUsecase_GetFollowing_Call) Return(_a0 []*domain.User, _a1 error) *MockIFollowUsecase_GetFollowing_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIFollowUsecase_GetFollowing_Call) RunAndReturn(run func(context.Context, string) ([]*domain.User, error)) *MockIFollowUsecase_GetFollowing_Call {
	_c.Call.Return(run)
	return _c
}

// IsFollowing provides a mock function with given fields: ctx, followerID, followeeID
func (_m *MockIFollowUsecase) IsFollowing(ctx context.Context, followerID string, followeeID string) (bool, error) {
	ret := _m.Called(ctx, followerID, followeeID)

	if len(ret) == 0 {
		panic("no return value specified for IsFollowing")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, followerID, followeeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, followerID, followeeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, followerID, followeeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIFollowUsecase_IsFollowing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFollowing'
type MockIFollowUsecase_IsFollowing_Call struct {
	*mock.Call
}

// IsFollowing is a helper method to define mock.On call
//   - ctx context.Context
//   - followerID string
//   - followeeID string
func (_e *MockIFollowUsecase_Expecter) IsFollowing(ctx interface{}, followerID interface{}, followeeID interface{}) *MockIFollowUsecase_IsFollowing_Call {
	return &MockIFollowUsecase_IsFollowing_Call{Call: _e.mock.On("IsFollowing", ctx, followerID, followeeID)}
}

func (_c *MockIFollowUsecase_IsFollowing_Call) Run(run func(ctx context.Context, followerID string, followeeID string)) *MockIFollowUsecase_IsFollowing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIFollowUsecase_IsFollowing_Call) Return(_a0 bool, _a1 error) *MockIFollowUsecase_IsFollowing_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIFollowUsecase_IsFollowing_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockIFollowUsecase_IsFollowing_Call {
	_c.Call.Return(run)
	return _c
}

// UnfollowUser provides a mock function with given fields: ctx, followerID, followeeID
func (_m *MockIFollowUsecase) UnfollowUser(ctx context.Context, followerID string, followeeID string) error {
	ret := _m.Called(ctx, followerID, followeeID)

	if len(ret) == 0 {
		panic("no return value specified for UnfollowUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, followerID, followeeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIFollowUsecase_UnfollowUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnfollowUser'
type MockIFollowUsecase_UnfollowUser_Call struct {
	*mock.Call
}

// UnfollowUser is a helper method to define mock.On call
//   - ctx context.Context
//   - followerID string
//   - followeeID string
func (_e *MockIFollowUsecase_Expecter) UnfollowUser(ctx interface{}, followerID interface{}, followeeID interface{}) *MockIFollowUsecase_UnfollowUser_Call {
	return &MockIFollowUsecase_UnfollowUser_Call{Call: _e.mock.On("UnfollowUser", ctx, followerID, followeeID)}
}

func (_c *MockIFollowUsecase_UnfollowUser_Call) Run(run func(ctx context.Context, followerID string, followeeID string)) *MockIFollowUsecase_UnfollowUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIFollowUsecase_UnfollowUser_Call) Return(_a0 error) *MockIFollowUsecase_UnfollowUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIFollowUsecase_UnfollowUser_Call) RunAndReturn(run func(context.Context, string, string) error) *MockIFollowUsecase_UnfollowUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIFollowUsecase creates a new instance of MockIFollowUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIFollowUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIFollowUsecase {
	mock := &MockIFollowUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
