// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockIPasswordService is an autogenerated mock type for the IPasswordService type
type MockIPasswordService struct {
	mock.Mock
}

type MockIPasswordService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPasswordService) EXPECT() *MockIPasswordService_Expecter {
	return &MockIPasswordService_Expecter{mock: &_m.Mock}
}

// HashPassword provides a mock function with given fields: password
func (_m *MockIPasswordService) HashPassword(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPasswordService_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type MockIPasswordService_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password string
func (_e *MockIPasswordService_Expecter) HashPassword(password interface{}) *MockIPasswordService_HashPassword_Call {
	return &MockIPasswordService_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *MockIPasswordService_HashPassword_Call) Run(run func(password string)) *MockIPasswordService_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIPasswordService_HashPassword_Call) Return(_a0 string, _a1 error) *MockIPasswordService_HashPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPasswordService_HashPassword_Call) RunAndReturn(run func(string) (string, error)) *MockIPasswordService_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

// IsPasswordStrong provides a mock function with given fields: password
func (_m *MockIPasswordService) IsPasswordStrong(password string) bool {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for IsPasswordStrong")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockIPasswordService_IsPasswordStrong_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPasswordStrong'
type MockIPasswordService_IsPasswordStrong_Call struct {
	*mock.Call
}

// IsPasswordStrong is a helper method to define mock.On call
//   - password string
func (_e *MockIPasswordService_Expecter) IsPasswordStrong(password interface{}) *MockIPasswordService_IsPasswordStrong_Call {
	return &MockIPasswordService_IsPasswordStrong_Call{Call: _e.mock.On("IsPasswordStrong", password)}
}

func (_c *MockIPasswordService_IsPasswordStrong_Call) Run(run func(password string)) *MockIPasswordService_IsPasswordStrong_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIPasswordService_IsPasswordStrong_Call) Return(_a0 bool) *MockIPasswordService_IsPasswordStrong_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPasswordService_IsPasswordStrong_Call) RunAndReturn(run func(string) bool) *MockIPasswordService_IsPasswordStrong_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPassword provides a mock function with given fields: hash, password
func (_m *MockIPasswordService) VerifyPassword(hash string, password string) bool {
	ret := _m.Called(hash, password)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(hash, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockIPasswordService_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type MockIPasswordService_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - hash string
//   - password string
func (_e *MockIPasswordService_Expecter) VerifyPassword(hash interface{}, password interface{}) *MockIPasswordService_VerifyPassword_Call {
	return &MockIPasswordService_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", hash, password)}
}

func (_c *MockIPasswordService_VerifyPassword_Call) Run(run func(hash string, password string)) *MockIPasswordService_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockIPasswordService_VerifyPassword_Call) Return(_a0 bool) *MockIPasswordService_VerifyPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPasswordService_VerifyPassword_Call) RunAndReturn(run func(string, string) bool) *MockIPasswordService_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIPasswordService creates a new instance of MockIPasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPasswordService {
	mock := &MockIPasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
