// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "write_base/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockIReportUsecase is an autogenerated mock type for the IReportUsecase type
type MockIReportUsecase struct {
	mock.Mock
}

type MockIReportUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIReportUsecase) EXPECT() *MockIReportUsecase_Expecter {
	return &MockIReportUsecase_Expecter{mock: &_m.Mock}
}

// CreateReport provides a mock function with given fields: ctx, report
func (_m *MockIReportUsecase) CreateReport(ctx context.Context, report *domain.Report) error {
	ret := _m.Called(ctx, report)

	if len(ret) == 0 {
		panic("no return value specified for CreateReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Report) error); ok {
		r0 = rf(ctx, report)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIReportUsecase_CreateReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReport'
type MockIReportUsecase_CreateReport_Call struct {
	*mock.Call
}

// CreateReport is a helper method to define mock.On call
//   - ctx context.Context
//   - report *domain.Report
func (_e *MockIReportUsecase_Expecter) CreateReport(ctx interface{}, report interface{}) *MockIReportUsecase_CreateReport_Call {
	return &MockIReportUsecase_CreateReport_Call{Call: _e.mock.On("CreateReport", ctx, report)}
}

func (_c *MockIReportUsecase_CreateReport_Call) Run(run func(ctx context.Context, report *domain.Report)) *MockIReportUsecase_CreateReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Report))
	})
	return _c
}

func (_c *MockIReportUsecase_CreateReport_Call) Return(_a0 error) *MockIReportUsecase_CreateReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIReportUsecase_CreateReport_Call) RunAndReturn(run func(context.Context, *domain.Report) error) *MockIReportUsecase_CreateReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetReports provides a mock function with given fields: ctx, filter
func (_m *MockIReportUsecase) GetReports(ctx context.Context, filter map[string]interface{}) ([]*domain.Report, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetReports")
	}

	var r0 []*domain.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) ([]*domain.Report, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) []*domain.Report); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Report)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIReportUsecase_GetReports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReports'
type MockIReportUsecase_GetReports_Call struct {
	*mock.Call
}

// GetReports is a helper method to define mock.On call
//   - ctx context.Context
//   - filter map[string]interface{}
func (_e *MockIReportUsecase_Expecter) GetReports(ctx interface{}, filter interface{}) *MockIReportUsecase_GetReports_Call {
	return &MockIReportUsecase_GetReports_Call{Call: _e.mock.On("GetReports", ctx, filter)}
}

func (_c *MockIReportUsecase_GetReports_Call) Run(run func(ctx context.Context, filter map[string]interface{})) *MockIReportUsecase_GetReports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]interface{}))
	})
	return _c
}

func (_c *MockIReportUsecase_GetReports_Call) Return(_a0 []*domain.Report, _a1 error) *MockIReportUsecase_GetReports_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIReportUsecase_GetReports_Call) RunAndReturn(run func(context.Context, map[string]interface{}) ([]*domain.Report, error)) *MockIReportUsecase_GetReports_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReportStatus provides a mock function with given fields: ctx, reportID, status
func (_m *MockIReportUsecase) UpdateReportStatus(ctx context.Context, reportID string, status domain.ReportStatus) error {
	ret := _m.Called(ctx, reportID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReportStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.ReportStatus) error); ok {
		r0 = rf(ctx, reportID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIReportUsecase_UpdateReportStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReportStatus'
type MockIReportUsecase_UpdateReportStatus_Call struct {
	*mock.Call
}

// UpdateReportStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - reportID string
//   - status domain.ReportStatus
func (_e *MockIReportUsecase_Expecter) UpdateReportStatus(ctx interface{}, reportID interface{}, status interface{}) *MockIReportUsecase_UpdateReportStatus_Call {
	return &MockIReportUsecase_UpdateReportStatus_Call{Call: _e.mock.On("UpdateReportStatus", ctx, reportID, status)}
}

func (_c *MockIReportUsecase_UpdateReportStatus_Call) Run(run func(ctx context.Context, reportID string, status domain.ReportStatus)) *MockIReportUsecase_UpdateReportStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.ReportStatus))
	})
	return _c
}

func (_c *MockIReportUsecase_UpdateReportStatus_Call) Return(_a0 error) *MockIReportUsecase_UpdateReportStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIReportUsecase_UpdateReportStatus_Call) RunAndReturn(run func(context.Context, string, domain.ReportStatus) error) *MockIReportUsecase_UpdateReportStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIReportUsecase creates a new instance of MockIReportUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIReportUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIReportUsecase {
	mock := &MockIReportUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
