// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	domain "write_base/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockITokenService is an autogenerated mock type for the ITokenService type
type MockITokenService struct {
	mock.Mock
}

type MockITokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITokenService) EXPECT() *MockITokenService_Expecter {
	return &MockITokenService_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function with given fields: user
func (_m *MockITokenService) GenerateAccessToken(user *domain.User) (string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.User) (string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(*domain.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*domain.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITokenService_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockITokenService_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - user *domain.User
func (_e *MockITokenService_Expecter) GenerateAccessToken(user interface{}) *MockITokenService_GenerateAccessToken_Call {
	return &MockITokenService_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", user)}
}

func (_c *MockITokenService_GenerateAccessToken_Call) Run(run func(user *domain.User)) *MockITokenService_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.User))
	})
	return _c
}

func (_c *MockITokenService_GenerateAccessToken_Call) Return(_a0 string, _a1 error) *MockITokenService_GenerateAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITokenService_GenerateAccessToken_Call) RunAndReturn(run func(*domain.User) (string, error)) *MockITokenService_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function with given fields: user
func (_m *MockITokenService) GenerateRefreshToken(user *domain.User) (string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.User) (string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(*domain.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*domain.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITokenService_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockITokenService_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
//   - user *domain.User
func (_e *MockITokenService_Expecter) GenerateRefreshToken(user interface{}) *MockITokenService_GenerateRefreshToken_Call {
	return &MockITokenService_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken", user)}
}

func (_c *MockITokenService_GenerateRefreshToken_Call) Run(run func(user *domain.User)) *MockITokenService_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.User))
	})
	return _c
}

func (_c *MockITokenService_GenerateRefreshToken_Call) Return(_a0 string, _a1 error) *MockITokenService_GenerateRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITokenService_GenerateRefreshToken_Call) RunAndReturn(run func(*domain.User) (string, error)) *MockITokenService_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function with given fields: token
func (_m *MockITokenService) ValidateAccessToken(token string) (*domain.AuthClaims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *domain.AuthClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.AuthClaims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.AuthClaims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITokenService_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockITokenService_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - token string
func (_e *MockITokenService_Expecter) ValidateAccessToken(token interface{}) *MockITokenService_ValidateAccessToken_Call {
	return &MockITokenService_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", token)}
}

func (_c *MockITokenService_ValidateAccessToken_Call) Run(run func(token string)) *MockITokenService_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockITokenService_ValidateAccessToken_Call) Return(_a0 *domain.AuthClaims, _a1 error) *MockITokenService_ValidateAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITokenService_ValidateAccessToken_Call) RunAndReturn(run func(string) (*domain.AuthClaims, error)) *MockITokenService_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function with given fields: token
func (_m *MockITokenService) ValidateRefreshToken(token string) (*domain.AuthClaims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 *domain.AuthClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.AuthClaims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.AuthClaims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITokenService_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type MockITokenService_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - token string
func (_e *MockITokenService_Expecter) ValidateRefreshToken(token interface{}) *MockITokenService_ValidateRefreshToken_Call {
	return &MockITokenService_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", token)}
}

func (_c *MockITokenService_ValidateRefreshToken_Call) Run(run func(token string)) *MockITokenService_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockITokenService_ValidateRefreshToken_Call) Return(_a0 *domain.AuthClaims, _a1 error) *MockITokenService_ValidateRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITokenService_ValidateRefreshToken_Call) RunAndReturn(run func(string) (*domain.AuthClaims, error)) *MockITokenService_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockITokenService creates a new instance of MockITokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITokenService {
	mock := &MockITokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
