with-expecter: true
dir: "./internal/mocks"
outpkg: "mocks"
filename: "{{.InterfaceName}}Mock.go"
packages:
  "write_base/internal/repository":
    config:
      all: true
  "write_base/internal/usecase":
    config:
      all: true
  "write_base/internal/domain":
    config:
      all: true
